### PR TITLE
Issue template for Feature requests

### PR DESCRIPTION
**Pull request by Yashesvinee**
What does this implement/fix? Explain your changes.
--------------------------------------------------
Added issue template for feature requests

Does this close any currently open issues?
------------------------------------------
Closes: Temperate-Designs/sunflower-dash#12

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

### CODE REVIEW

**Comment by Yashesvinee** [comment]
@nicolasbock I made the template in yaml format. I hope that is okay. Please let me know if it requires any changes

**Review by ajlabock — APPROVED** [review]
💯

**Review by adisbock — APPROVED** [review]

**Comment by nicolasbock** [comment]
> @nicolasbock I made the template in yaml format. I hope that is okay. Please let me know if it requires any changes

Thank you @Yashesvinee !

**Review by nicolasbock — APPROVED** [review]
LGTM

**Pull request merged**
