### PR TITLE
Closes: Temperate-Designs/sunflower-dash#15

### PR DESCRIPTION
**Pull request by Perpetual-Incantation**
Added GitHub Issues Badge to README #15

### CODE REVIEW

**Review by AnirbanBall — APPROVED** [review]
Looking good to me 🎉 .Can be merged ✌

**Review by AnirbanBall — APPROVED** [review]

**Comment by nicolasbock** [comment]
Thanks @Perpetual-Incantation !

And thanks @AnirbanBall for the review :)

**Comment by Perpetual-Incantation** [comment]
Will this be counted in hactober?

**Comment by nicolasbock** [comment]
I think so. The project has the `hacktoberfest` label. Please check at

https://hacktoberfest.digitalocean.com/profile

And let me know whether your pull request was counted.

**Pull request merged**
